export const SET_POST = "SET_POST";
export const SET_POST_COMMENT = "SET_POST_COMMENT";
export const SET_POST_IMAGE_VIEW = "SET_POST_IMAGE_VIEW";

export const POST_UPLOAD_REQUEST = "POST_UPLOAD_REQUEST";
export const POST_UPLOAD_FAILURE = "POST_UPLOAD_FAILURE";
export const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";

export const POST_COMMENT_UPLOAD_REQUEST = "POST_COMMENT_UPLOAD_REQUEST";
export const POST_COMMENT_UPLOAD_FAILURE = "POST_COMMENT_UPLOAD_FAILURE";
export const POST_COMMENT_UPLOAD_SUCCESS = "POST_COMMENT_UPLOAD_SUCCESS";

export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

export const POST_COMMENT_DELETE_REQUEST = "POST_COMMENT_DELETE_REQUEST";
export const POST_COMMENT_DELETE_SUCCESS = "POST_COMMENT_DELETE_SUCCESS";
export const POST_COMMENT_DELETE_FAILURE = "POST_COMMENT_DELETE_FAILURE";

export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";

export const POST_COMMENT_UPDATE_REQUEST = "POST_COMMENT_UPDATE_REQUEST";
export const POST_COMMENT_UPDATE_SUCCESS = "POST_COMMENT_UPDATE_SUCCESS";
export const POST_COMMENT_UPDATE_FAILURE = "POST_COMMENT_UPDATE_FAILURE";


