export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const UPLOAD_DELETE_REQUEST = "UPLOAD_DELETE_REQUEST";
export const UPLOAD_DELETE_SUCCESS = "UPLOAD_DELETE_SUCCESS";
export const UPLOAD_DELETE_FAILURE = "UPLOAD_DELETE_FAILURE";

